program ProRock.Soapite.CheckVatServiceSample;

{$APPTYPE CONSOLE}

// ProRock.Soapite.CheckVatService and ProRock.Xmlite.Schema.CheckVatService are generated by ProRocket from checkVatService.wsdl
// (EU VIES - VAT number validation); the client unit re-exports everything the calls need, so it is the only one to use.
// Usage: ProRock.Soapite.CheckVatServiceSample [-xml] [VAT numbers with country prefix, e.g. IE6388047V DE123456789]

uses
  System.SysUtils,
  ProRock.Xmlite.Schema.CheckVatService in 'ProRock.Xmlite.Schema.CheckVatService.pas',
  ProRock.Soapite.CheckVatService in 'ProRock.Soapite.CheckVatService.pas';

const
  // the WSDL still declares http://, the live service is the same over https
  cViesEndpoint = 'https://ec.europa.eu/taxation_customs/vies/services/checkVatService';

  // with no numbers given: a registered one and an invalid input (the service answers INVALID_INPUT with a SOAP Fault)
  cDemoNumbers: array[0..1] of string = ('IE6388047V', 'XX123');

type
  // raw SOAP xml to the console - run with -xml
  TLog = class
  public
    class procedure Request(aSender: TObject; const aXml: string);
    class procedure Response(aSender: TObject; const aXml: string);
  end;

{ TLog }

class procedure TLog.Request(aSender: TObject; const aXml: string);
begin
  Writeln('  >> ', aXml);
end;

class procedure TLog.Response(aSender: TObject; const aXml: string);
begin
  Writeln('  << ', aXml);
end;

// TryMethod: no exceptions - the response (yours to free), or the reason in error
procedure CheckVat(aService: TCheckVatService; const aVat: string);
begin
  var request: TCheckVatE := TCheckVatE.Create;
  try
    request.CountryCode := aVat.Substring(0, 2).ToUpper;
    request.VatNumber := aVat.Substring(2);

    var response: TCheckVatResponseE;
    var error: TSoapiteError;
    if aService.TryCheckVat(request, response, error) then
      try
        if response.Valid then
          Writeln(Format('%s: valid - %s, %s', [aVat, response.Name, string(response.Address).Replace(#10, ', ')]))
        else
          Writeln(Format('%s: not valid', [aVat]));
      finally
        response.Free;
      end
    else
      Writeln(Format('%s: failed [%s]: %s', [aVat, error.Code, error.Message.Split([#13, #10])[0]]));
  finally
    request.Free;
  end;
end;

begin
  ReportMemoryLeaksOnShutdown := True;

  try
    var service: TCheckVatService := TCheckVatService.Create(cViesEndpoint);
    try
      if FindCmdLineSwitch('xml') then
      begin
        service.OnRequest := TLog.Request;
        service.OnResponse := TLog.Response;
      end;

      var checked: boolean := False;
      for var i := 1 to ParamCount do
        if not ParamStr(i).IsEmpty and not CharInSet(ParamStr(i)[1], SwitchChars) then
        begin
          CheckVat(service, ParamStr(i));
          checked := True;
        end;

      if not checked then
        for var vat: string in cDemoNumbers do
          CheckVat(service, vat);
    finally
      service.Free;
    end;
  except
    on e: Exception do
      Writeln(e.ClassName, ': ', e.Message);
  end;

  Write('Press <Enter> to quit.');
  Readln;
end.
