program ProRock.Soapite.CalculatorSample;

{$APPTYPE CONSOLE}

// ProRock.Soapite.Calculator and ProRock.Xmlite.Schema.Calculator are generated by ProRocket from calculator.wsdl;
// the client unit re-exports everything the calls need (TAddE, TAddResponseE, ..., TSoapiteError), so it is the only one to use;
// ProRock.Soapite is here just for sv12 - run with -soap12 to talk SOAP 1.2 (the service declares both versions), -xml to see it

uses
  System.SysUtils,
  ProRock.Soapite,
  ProRock.Xmlite.Schema.Calculator in 'ProRock.Xmlite.Schema.Calculator.pas',
  ProRock.Soapite.Calculator in 'ProRock.Soapite.Calculator.pas';

type
  // raw SOAP xml to the console - run with -xml
  TLog = class
  public
    class procedure Request(aSender: TObject; const aXml: string);
    class procedure Response(aSender: TObject; const aXml: string);
  end;

{ TLog }

class procedure TLog.Request(aSender: TObject; const aXml: string);
begin
  Writeln('  >> ', aXml);
end;

class procedure TLog.Response(aSender: TObject; const aXml: string);
begin
  Writeln('  << ', aXml);
end;

// Method: raises ESoapiteFault/ESoapiteTransport on failure; the returned response is yours to free
function Add(aCalculator: TCalculator; aIntA, aIntB: integer): integer;
begin
  var request: TAddE := TAddE.Create;
  try
    request.IntA := aIntA;
    request.IntB := aIntB;

    var response: TAddResponseE := aCalculator.Add(request);
    try
      Result := response.AddResult;
    finally
      response.Free;
    end;
  finally
    request.Free;
  end;
end;

// TryMethod: no exceptions - the response (yours to free), or the reason in error
procedure Divide(aCalculator: TCalculator; aIntA, aIntB: integer);
begin
  var request: TDivideE := TDivideE.Create;
  try
    request.IntA := aIntA;
    request.IntB := aIntB;

    var response: TDivideResponseE;
    var error: TSoapiteError;
    if aCalculator.TryDivide(request, response, error) then
      try
        Writeln(Format('%d / %d = %d', [aIntA, aIntB, response.DivideResult]));
      finally
        response.Free;
      end
    else
      Writeln(Format('%d / %d -> failed [%s]: %s', [aIntA, aIntB, error.Code, error.Message.Split([#13, #10])[0]]));
  finally
    request.Free;
  end;
end;

begin
  ReportMemoryLeaksOnShutdown := True;

  try
    var calculator: TCalculator := TCalculator.Create;
    try
      if FindCmdLineSwitch('xml') then
      begin
        calculator.OnRequest := TLog.Request;
        calculator.OnResponse := TLog.Response;
      end;

      if FindCmdLineSwitch('soap12') then
        calculator.SoapVersion := sv12;
      if calculator.SoapVersion = sv12 then
        Writeln('SOAP 1.2')
      else
        Writeln('SOAP 1.1');

      Writeln('2 + 3 = ', Add(calculator, 2, 3));
      Writeln('0 + 5 = ', Add(calculator, 0, 5), '  (required intA = 0 is sent)');

      Divide(calculator, 8, 2);
      Divide(calculator, 1, 0); // the service answers with a SOAP Fault - no exception, just the reason
    finally
      calculator.Free;
    end;
  except
    on e: Exception do
      Writeln(e.ClassName, ': ', e.Message);
  end;

  Write('Press <Enter> to quit.');
  Readln;
end.
